# Uncomment the next line to define a global platform for your project
# platform :ios, '16.0'

target 'Memorizer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Memorizer
  pod 'SwiftLint', '~> 0.50'
  pod 'R.swift', '~> 7.3'

end
